name: llm_chat
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  auto_route: ^7.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.2.0+1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  hooks_riverpod: ^2.3.6
  http: ^1.2.1
  intl: any
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  syncfusion_flutter_charts: ^21.2.8

dev_dependencies:
  auto_route_generator: ^7.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.4
  custom_lint: null
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  riverpod_lint: ^2.1.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
